services:
  # EventListener + Service automatisch laden
  MummertMedia\ContaoMeilisearchBundle\:
    resource: '../../*'
    autowire: true
    autoconfigure: true
    public: true

  # IndexPageListener als Contao-Hook registrieren
  MummertMedia\ContaoMeilisearchBundle\EventListener\IndexPageListener:
    tags:
      - { name: contao.hook, hook: indexPage, method: onIndexPage }
      -
  MummertMedia\ContaoMeilisearchBundle\Cron\MeilisearchIndexCron:
    tags:
      - { name: contao.cron, interval: daily }