services:
  # EventListener + Service automatisch laden
  MummertMedia\ContaoMeilisearchBundle\:
    resource: '../../{EventListener,Service}/*'
    autowire: true
    autoconfigure: true
    public: true

  # IndexPageListener als Contao-Hook registrieren
  MummertMedia\ContaoMeilisearchBundle\EventListener\IndexPageListener:
    tags:
      - { name: contao.hook, hook: indexPage, method: onIndexPage }

  MummertMedia\ContaoMeilisearchBundle\EventListener\PdfCleanupListener:
    tags:
      - { name: kernel.event_listener, event: terminal42.escargot.last_chunk, method: onLastChunk }