services:
  _defaults:
    autowire: true
    autoconfigure: true

  MummertMedia\ContaoMeilisearchBundle\Migration\ExtendTlSearchMigration:
    arguments:
      - '@database_connection'
    tags:
      - { name: contao.migration }