services:
  # nur echte PHP-Klassen laden, NICHT Resources
  MummertMedia\ContaoMeilisearchBundle\:
    resource: '../../{EventListener,Service}/*'
    autowire: true
    autoconfigure: true
    public: true