services:
  MummertMedia\ContaoMeilisearchBundle\:
    resource: '../../{Command,Cron,EventListener,Service}'
    autowire: true
    autoconfigure: true

  MummertMedia\ContaoMeilisearchBundle\EventListener\IndexPageListener:
    autowire: true
    autoconfigure: false
    tags:
      - { name: contao.hook, hook: indexPage, method: onIndexPage }

  MummertMedia\ContaoMeilisearchBundle\Cron\MeilisearchIndexCron:
    tags:
      - { name: contao.cron, interval: daily }
