services:
  # Alias MUSS vorhanden sein (richtig platziert)
  Psr\Container\ContainerInterface: '@service_container'

  MummertMedia\ContaoMeilisearchBundle\:
    resource: '../../{Command,Cron,EventListener,Service}'
    autowire: true
    autoconfigure: true

  MummertMedia\ContaoMeilisearchBundle\EventListener\IndexPageListener:
    autowire: true
    autoconfigure: false
    tags:
      - { name: contao.hook, hook: indexPage, method: onIndexPage }

  MummertMedia\ContaoMeilisearchBundle\Cron\MeilisearchIndexCron:
    tags:
      - { name: contao.cron, interval: daily }

  MummertMedia\ContaoMeilisearchBundle\Controller\FrontendModule\MeilisearchSearchController:
    autowire: true
    autoconfigure: false
    tags:
      - { name: contao.frontend_module, type: meilisearch_search, category: search }