services:
  MummertMedia\ContaoMeilisearchBundle\Service\SearchDataProvider: ~

  MummertMedia\ContaoMeilisearchBundle\EventListener\IndexPageListener:
    tags:
      - { name: contao.hook, hook: indexPage, method: onIndexPage }