services:
  MummertMedia\ContaoMeilisearchBundle\:
    resource: '../../{Command,Cron,EventListener,Service}'
    autowire: true
    autoconfigure: true

  # IndexPageListener als Contao-Hook
  MummertMedia\ContaoMeilisearchBundle\EventListener\IndexPageListener:
    tags:
      - { name: contao.hook, hook: indexPage, method: onIndexPage }

  # t√§glicher Reindex
  MummertMedia\ContaoMeilisearchBundle\Cron\MeilisearchIndexCron:
    tags:
      - { name: contao.cron, interval: daily }